### ISSUE TITLE
Connection should support timeout option

### ISSUE THREAD

**Issue by dchandekstark** [samvera/active_fedora#1105]
We are monkey patching v9.8.2 this way:

``` ruby
class ActiveFedora::Fedora
  def authorized_connection
    options = {}
    if @config[:timeout]
      options[:request] = { timeout: @config[:timeout].to_i }
    end
    connection = Faraday.new(host, options)
    connection.basic_auth(user, password)
    connection
  end
end
```

**Comment by jrochkind** [comment]
@dchandekstark how do you then use this monkey patch?  The timeout config is in your fedora.yml or whatever?

**Comment by cjcolvar** [comment]
@jrochkind @dchandekstark AF now has a way to supply this timeout: https://github.com/samvera/active_fedora/commit/a58168680214f8a93ff7e46e9b8b21bb4939ebad (#1271)

You do this by specifying time outs (in seconds) in your fedora.yml:
```
development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 8984 %>/rest
  base_path: /dev
  request: { timeout: 600, open_timeout: 60}
```
