### ISSUE TITLE
Rubydora 1.7.2 compatibility with AF 7.0.0

### ISSUE THREAD

**Issue by dchandekstark** [samvera/active_fedora#353]
AF 7.0.0.rc2 CI build has test failures with Rubydora 1.7.2:

```
Failures:

  1) ActiveFedora::Base sharding When the repository is NOT sharded 
     Failure/Error: subject {ActiveFedora::Base.connection_for_pid('test:bar')}
     RuntimeError:
       You're connecting to a Fedora 0.0 repository. Rubydora requires Fedora >= 3.4
     # ./lib/active_fedora/rubydora_connection.rb:19:in `connect'
     # ./lib/active_fedora/rubydora_connection.rb:11:in `initialize'
     # ./lib/active_fedora/sharding.rb:20:in `new'
     # ./lib/active_fedora/sharding.rb:20:in `connection_for_pid'
     # ./spec/unit/base_spec.rb:19:in `block (4 levels) in <top (required)>'
     # ./spec/unit/base_spec.rb:25:in `block (4 levels) in <top (required)>'

  2) ActiveFedora::Base sharding When the repository is NOT sharded should be the standard connection
     Failure/Error: subject {ActiveFedora::Base.connection_for_pid('test:bar')}
     RuntimeError:
       You're connecting to a Fedora 0.0 repository. Rubydora requires Fedora >= 3.4
     # ./lib/active_fedora/rubydora_connection.rb:19:in `connect'
     # ./lib/active_fedora/rubydora_connection.rb:11:in `initialize'
     # ./lib/active_fedora/sharding.rb:20:in `new'
     # ./lib/active_fedora/sharding.rb:20:in `connection_for_pid'
     # ./spec/unit/base_spec.rb:19:in `block (4 levels) in <top (required)>'
     # ./spec/unit/base_spec.rb:27:in `block (4 levels) in <top (required)>'

  3) ActiveFedora::Base sharding When the repository is sharded the repository for test:bar should be shard1
     Failure/Error: subject {ActiveFedora::Base.connection_for_pid('test:bar')}
     RuntimeError:
       You're connecting to a Fedora 0.0 repository. Rubydora requires Fedora >= 3.4
     # ./lib/active_fedora/rubydora_connection.rb:19:in `connect'
     # ./lib/active_fedora/rubydora_connection.rb:11:in `initialize'
     # ./lib/active_fedora/sharding.rb:18:in `new'
     # ./lib/active_fedora/sharding.rb:18:in `connection_for_pid'
     # ./spec/unit/base_spec.rb:70:in `block (6 levels) in <top (required)>'
     # ./spec/unit/base_spec.rb:72:in `block (6 levels) in <top (required)>'

  4) ActiveFedora::Base sharding When the repository is sharded the repository for test:baz should be shard1
     Failure/Error: subject {ActiveFedora::Base.connection_for_pid('test:nanana')}
     RuntimeError:
       You're connecting to a Fedora 0.0 repository. Rubydora requires Fedora >= 3.4
     # ./lib/active_fedora/rubydora_connection.rb:19:in `connect'
     # ./lib/active_fedora/rubydora_connection.rb:11:in `initialize'
     # ./lib/active_fedora/sharding.rb:18:in `new'
     # ./lib/active_fedora/sharding.rb:18:in `connection_for_pid'
     # ./spec/unit/base_spec.rb:76:in `block (6 levels) in <top (required)>'
     # ./spec/unit/base_spec.rb:78:in `block (6 levels) in <top (required)>'
```
