### ISSUE TITLE
Rubydora 1.7.2 compatibility with AF 6.7.6

### ISSUE THREAD

**Issue by dchandekstark** [samvera/active_fedora#354]
```
Failures:

  1) ActiveFedora::OmDatastream a new instance with an inline datastream #changed? should not be changed if the new xml matches the old xml
     Failure/Error: @obj.descMetadata.should_not be_changed
       expected changed? to return false, got true
     # ./spec/integration/om_datastream_spec.rb:42:in `block (4 levels) in <top (required)>'

  2) ActiveFedora::OmDatastream an instance that is a managed datastream #changed? should not be changed if the new xml matches the old xml
     Failure/Error: @obj.descMetadata.should_not be_changed
       expected changed? to return false, got true
     # ./spec/integration/om_datastream_spec.rb:84:in `block (4 levels) in <top (required)>'

  3) ActiveFedora::Base sharding When the repository is NOT sharded 
     Failure/Error: subject {ActiveFedora::Base.connection_for_pid('test:bar')}
     RuntimeError:
       You're connecting to a Fedora 0.0 repository. Rubydora requires Fedora >= 3.4
     # ./lib/active_fedora/rubydora_connection.rb:19:in `connect'
     # ./lib/active_fedora/rubydora_connection.rb:11:in `initialize'
     # ./lib/active_fedora/base.rb:137:in `new'
     # ./lib/active_fedora/base.rb:137:in `connection_for_pid'
     # ./spec/unit/base_spec.rb:19:in `block (4 levels) in <top (required)>'
     # ./spec/unit/base_spec.rb:25:in `block (4 levels) in <top (required)>'

  4) ActiveFedora::Base sharding When the repository is NOT sharded should be the standard connection
     Failure/Error: subject {ActiveFedora::Base.connection_for_pid('test:bar')}
     RuntimeError:
       You're connecting to a Fedora 0.0 repository. Rubydora requires Fedora >= 3.4
     # ./lib/active_fedora/rubydora_connection.rb:19:in `connect'
     # ./lib/active_fedora/rubydora_connection.rb:11:in `initialize'
     # ./lib/active_fedora/base.rb:137:in `new'
     # ./lib/active_fedora/base.rb:137:in `connection_for_pid'
     # ./spec/unit/base_spec.rb:19:in `block (4 levels) in <top (required)>'
     # ./spec/unit/base_spec.rb:27:in `block (4 levels) in <top (required)>'

  5) ActiveFedora::Base sharding When the repository is sharded the repository for test:bar should be shard1
     Failure/Error: subject {ActiveFedora::Base.connection_for_pid('test:bar')}
     RuntimeError:
       You're connecting to a Fedora 0.0 repository. Rubydora requires Fedora >= 3.4
     # ./lib/active_fedora/rubydora_connection.rb:19:in `connect'
     # ./lib/active_fedora/rubydora_connection.rb:11:in `initialize'
     # ./lib/active_fedora/base.rb:135:in `new'
     # ./lib/active_fedora/base.rb:135:in `connection_for_pid'
     # ./spec/unit/base_spec.rb:70:in `block (6 levels) in <top (required)>'
     # ./spec/unit/base_spec.rb:72:in `block (6 levels) in <top (required)>'

  6) ActiveFedora::Base sharding When the repository is sharded the repository for test:baz should be shard1
     Failure/Error: subject {ActiveFedora::Base.connection_for_pid('test:nanana')}
     RuntimeError:
       You're connecting to a Fedora 0.0 repository. Rubydora requires Fedora >= 3.4
     # ./lib/active_fedora/rubydora_connection.rb:19:in `connect'
     # ./lib/active_fedora/rubydora_connection.rb:11:in `initialize'
     # ./lib/active_fedora/base.rb:135:in `new'
     # ./lib/active_fedora/base.rb:135:in `connection_for_pid'
     # ./spec/unit/base_spec.rb:76:in `block (6 levels) in <top (required)>'
     # ./spec/unit/base_spec.rb:78:in `block (6 levels) in <top (required)>'

  7) ActiveFedora::Datastream#validate_content_present should expect content on a Managed (M) datastream
     Failure/Error: @test_datastream.validate_content_present.should be_false
       expected: false value
            got: true
     # ./spec/unit/datastream_spec.rb:42:in `block (3 levels) in <top (required)>'
```
